name: pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : install_poetry
        run: |
          pip install poetry
          make install
      - name : build_pack
        run: |
          make build
      - name : test flake8
        run: |
          make lint
