name: pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : install_poetry
        run: |
          pip install poetry
      - name : make install  
        run: |  
          make install
      - name : test flake8
        run: |
          make lint
